TASKS:
  'vitatrack':
    input_rna: /lustre/groups/ml01/workspace/anastasia.litinetskaya/code/vitatrack/datasets/V11L12-038_A1.RNA_MOSCOT_paired_hvg.h5ad
    input_metabolomics: /lustre/groups/ml01/workspace/anastasia.litinetskaya/code/vitatrack/datasets/V11L12-038_A1.MSI_MOSCOT_paired_hvg.h5ad
    methods:
      ridge:
        params: params/ridge_params.tsv
        featsel:
          - hvg
          - hvg_svd
          - hvg_svd_graph
          - svd
          - svd_graph
      lasso:
        params: params/lasso_params.tsv
        featsel:
          - hvg
          - hvg_svd
          - hvg_svd_graph
          - svd
          - svd_graph
      linear:
        params: params/linreg_params.tsv
        featsel:
          - hvg
          - hvg_svd
          - hvg_svd_graph
          - svd
          - svd_graph
      xgboost:
        params: params/xgboost_params.tsv
        featsel:
          # - hvg
          - hvg_svd
          - hvg_svd_graph
          - svd
          - svd_graph
